#%RAML 1.0
version: v1
title: Online OCR API

traits:
   client-id-required:
    headers:
      client_id:
        type: string
      client_secret:
        type: string

types:
  OCRResult:  
    properties: 
      text:
        type: string

/translate: 
  post: 
    is: [ client-id-required ]
    body:
      multipart/form-data:
        properties: 
          file1: 
            description: The file to translate to text 
            required: true 
            type: file 
            fileTypes: [ 'image/jpeg']   
          language:
            description: The language code for the file - ISO 639-1 Language Codes
            required: true
            enum: [ 'en' ]  
          contentType:
            description: The type of the file
            required: true
            type: string
          fileName:
            description: The name of the file
            required: true
            type: string
    responses: 
      200:
        body: 
          application/json:
            type: OCRResult
            description: The translated text
            example: |
              {
                "text": "Application form XYZ"
              }
            